name: Deploy Website Redirect Infrastructure

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_TERRAFORM_BUCKET:
        required: true
    inputs:
      ENVIRONMENT:
        description: application environment (production, preprod, qa, development)
        type: string
        required: false
        default: development
      SERVICE_NAME:
        description: service name calling this workflow
        type: string
        required: true
      SUBDOMAIN:
        description: website subdomain
        type: string
        required: false
        default: ""
      DOMAIN:
        description: webite domain
        type: string
        required: true
      REDIRECT:
        description: website to redirect to
        type: string
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      working-directory: ./configure-aws-s3-website/src
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: Migas99/configure-aws-s3-website
          path: configure-aws-s3-website

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: npm install
      
      - name: Install Terraform CDK
        run: npm install --global cdktf-cli@0.12.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ env.AWS_REGION }}

      - name: Deploy with Terraform CDK
        working-directory: ${{ env.working-directory }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_TERRAFORM_BUCKET: ${{ secrets.AWS_TERRAFORM_BUCKET }}
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
          SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
          SUBDOMAIN: ${{ inputs.SUBDOMAIN }}
          DOMAIN: ${{ inputs.DOMAIN }}
          REDIRECT: ${{ inputs.REDIRECT }}
        run: cdktf deploy --auto-approve website-redirect-stack