name: Run Linting and Infrastructures' Unit Tests
on:
  pull_request:
    paths: 
      - "**"
jobs:
  deploy:
    name: Run Terraform CDK Unit Tests
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: npm install
      - name: Install Terraform CDK
        run: npm install --global cdktf-cli@0.12.2
      # - name: Run ESLint
      #   working-directory: ${{ env.working-directory }}
      #   run: npm run lint
      - name: Run Terraform CDK Unit Tests
        working-directory: ${{ env.working-directory }}
        run: npm run test